# https://taskfile.dev
version: '3'

vars:
      GITHUB_ORG: hoveytechllc
      REPO_NAME: visio-stencil-creator
      TAG_NAME: v1.0
      GCR_REPO: staging-k8s.gcr.io/{{.REPO_NAME}}:{{.TAG_NAME}}

tasks:
  build:oci:
    cmds:
      - rm -fdr ./build/{{.REPO_NAME}}
      - git clone --branch release/{{.TAG_NAME}} https://github.com/{{.GITHUB_ORG}}/{{.REPO_NAME}}.git ./tools/{{.REPO_NAME}}
      # build image using Dockerfile from github repository
      # Tag resulting image for pushing
      - |
        docker build \
          -t {{.GCR_REPO}} \
          -f ./containers/{{.REPO_NAME}}/Dockerfile \
          ./containers/{{.REPO_NAME}}
      # Clean up source code
      - rm -fdr ./containers/{{.REPO_NAME}}
      - docker push {{.GCR_REPO}}

  rasterize:
    vars:
      IMAGE_SIZE:
        - 128
        - 256
        - 512
    cmds:
      - docker build -t svgconvertor:latest -f containers/{{.REPO_NAME}}/Dockerfile .
      - |
        total=$(find icons/svg/ -name *.svg | wc -l)
        counter=1
        {{range $index, $size := .IMAGE_SIZE}}
        for svg in $(find icons/svg/ -name *.svg | cut -b 5-)
        do
          dir=$(dirname -- ${svg})
          # echo "Create directory \"icons/png/${dir}\""
          mkdir -p icons/png/${dir}
          output=icons/png/${svg%%.*}-{{$size}}.png
          echo "[$counter/$total] Generating $output"
          docker run -v $(pwd)/svg:/convertor svgconvertor:latest  $svg -w {{$size}} > $output
          counter=$[$counter +1]
        done
        {{end}}

  update:
    vars:
      ICONS_PATH:
        sh: pwd
      DOCKER_IMAGE_REPO: k8s.gcr.io/visio-stencil-creator:v1.0
    cmds:
      # Run docker image that generates Visio stencil
      # using png images.
      - |
        docker run \
          -v ${ICONS_PATH}:/app/content \
          ${DOCKER_IMAGE_REPO} \
          "--image-pattern=**/labeled/*-256.png" \
          "--image-path=/app/content/png" \
          "--output-filename=/app/content/visio/network-architecture-stencils.vssx"

  default:
    cmds:
      - task: rasterize
      - task: update